### PR TITLE
fix!: expose all fields from response

### LINKED ISSUE #58: invalid response when using with additionalClaims / targetAudience
```js
        .then(r => {
          const body = r.data;
          this.rawToken = body;
          this.token = body.access_token;
          this.expiresAt = (iat + body.expires_in) * 1000;
          return this.token;
        })
```

That part of the code assumes that body has access_token, however, this is not the case when we want to auth through IAP and set targetAudience as an additionalClaim. Resulting body would simply
contain the following:

```
{ id_token: 'signed-jwt-token' }
```

Please provide a way to deal with it

### PR DESCRIPTION
**Pull request by JustinBeckwith**
BREAKING CHANGE: This commit creates multiple breaking changes. The `getToken()`
method previously returned `Promise<string>`, where the string was the
`access_token` returned from the response.  However, the `oauth2` endpoint could
return a variety of other fields, such as an `id_token` in special cases.

```js
const token = await getToken();
// old response: 'some.access.token'
// new response: { access_token: 'some.access.token'}
```

To further support this change, the `GoogleToken` class no longer exposes
a `token` variable.  It now exposes `rawToken`, `accessToken`, and `idToken`
fields which can be used to access the relevant values returned in the
response.

Fixes #58.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -57,15 +59,26 @@ class ErrorWithCode extends Error {
 let getPem: ((filename: string) => Promise<string>) | undefined;
 
 export class GoogleToken {
-  token?: string | null = null;
-  expiresAt?: number | null = null;
+  get accessToken() {
+    return this.rawToken ? this.rawToken.access_token : undefined;
```
Comment (JustinBeckwith) [inline src/index.ts]: @bcoe my kingdom for a null check operator
