### PR TITLE
fix!: update token endpoints to non-deprecated endpoints

### LINKED ISSUE #388: Move away from /v4 token endpoint to https://oauth2.googleapis.com/token
> Nit: we're trying to centralize the different token exchange endpoints to 'https://oauth2.googleapis.com/token', even though this is a mock, it might be good for new code to just show that one, unless you think it would be confusing to have different endpoints in the code if elsewhere you're using the one you have here.

CC: @silvolu 
Refs: https://github.com/googleapis/google-auth-library-nodejs/pull/1207/files#r674094849

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/node-gtoken/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #388  🦕

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
Both of the endpoints changed in this PR are marked as `deprecated` / `extremely deprecated` per documentation. Please feel free to reach out for more information. 

I also cleaned up some unused variables in tests that were giving linter warnings.

**Review by danielbankhead — APPROVED** [review]

File: src/index.ts [hunk 1]
```diff
@@ -21,9 +21,9 @@ const readFile = fs.readFile
       );
     };
 
-const GOOGLE_TOKEN_URL = 'https://www.googleapis.com/oauth2/v4/token';
+const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token';
 const GOOGLE_REVOKE_TOKEN_URL =
-  'https://accounts.google.com/o/oauth2/revoke?token=';
+  'https://oauth2.googleapis.com/token/revoke?token=';
```
Comment (sai-sunder-s) [inline src/index.ts:26]: where did you get this revoke url from?

Comment (ddelgrosso1) [reply src/index.ts:26]: In the documentation it said that the revoke old url (accounts.google.com) was `extremely deprecated`, so I browsed through the proto from the yaqs issue and saw revoke was in there.

Comment (sai-sunder-s) [reply src/index.ts:26]: Got it. As long as it works, it should be ok.

File: src/index.ts [hunk 2]
```diff
@@ -21,9 +21,8 @@ const readFile = fs.readFile
       );
     };
 
-const GOOGLE_TOKEN_URL = 'https://www.googleapis.com/oauth2/v4/token';
-const GOOGLE_REVOKE_TOKEN_URL =
-  'https://accounts.google.com/o/oauth2/revoke?token=';
+const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token';
```
Comment (ddelgrosso1) [inline src/index.ts:24]: https://github.com/googleapis/google-api-php-client/blob/7a95ed29e4b6c6859d2d22300c5455a92e2622ad/src/Client.php#L56

File: src/index.ts [hunk 3]
```diff
@@ -21,9 +21,8 @@ const readFile = fs.readFile
...
+const GOOGLE_REVOKE_TOKEN_URL = 'https://oauth2.googleapis.com/revoke?token=';
```
Comment (ddelgrosso1) [inline src/index.ts:25]: https://github.com/googleapis/google-auth-library-ruby/blob/2574faf1474711e581cdfde508387630ea3c4b8f/lib/googleauth/user_refresh.rb#L36

**Review by danielbankhead — APPROVED** [review]

**Review by d-goog — APPROVED** [review]

**Review by sofisl — APPROVED** [review]

**Comment by d-goog** [comment]
Merged and will further test this in auth downstream via the release candidate of this library.
